gardener/gardener-extension-shoot-networking-filter

- .reuse/dep5
- LICENSES/BSD-2-Clause.txt
- LICENSES/BSD-3-Clause.txt
- LICENSES/ISC.txt
- LICENSES/LicenseRef-PUBLIC-DOMAIN-xi2-xy.txt
- LICENSES/MIT.txt
- LICENSES/MPL-2.0.txt
- example/controller-registration.yaml
- pkg/metrics/metrics.go
Achieve REUSE compliance for this repo
The README claims that the project is REUSE compliant but "reuse lint" found missing license and copyright attributions
```other developer
Make project REUSE compliant, see https://reuse.software/
```
> Add missing license and copyright attributions

- pkg/controller/lifecycle/filter.go
- pkg/controller/lifecycle/filterlistprovider.go
Fixed bug in the filtering of the block list and added logging.
The filtering of the private ip ranges was broken in that it did only check
for overlap in one direction which could leave overlaps undetected if the
range coming from the block list is bigger and not starting at the same ip.
A check in both directions should do the trick.
Furthermore, added logging so that it is visible when a block list entry is
ignored due to overlap with a reserved range.
None.
```feature user
```
> Fixed bug in the filtering of the block list and added logging.

- hack/api-reference/config.md
- pkg/apis/config/types.go
- pkg/apis/config/v1alpha1/types.go
- pkg/apis/config/v1alpha1/zz_generated.conversion.go
- pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/config/zz_generated.deepcopy.go
- pkg/controller/lifecycle/actuator.go
Add pod security policy as egress-filter-applier daemon set needs `NET_ADMIN` capability.
Fixes #
```bugfix operator
Add pod security policy for egress-filter-applier daemon set 
```
> Add pod security policy

- pkg/controller/lifecycle/actuator.go
`PodSecurityPolicy` is deprecated and will be disabled in kubernetes v1.25+.
End-users are provided an option to migrate their PSPs before upgrading and disable the `PodSecurityPolicy` admission plugin in the ShootSpec. 
In that case, we should stop deploying our PSPs as well.
- This PR stops deploying PSPs related to `shoot-networking-filter` if the plugin is disabled in the Shoot.
Part of https://github.com/gardener/gardener/issues/5250
```breaking operator
Please make sure you're running gardener@v1.52 or above before upgrading to this version.
```
> Don't deploy `PSP`s when `PodSecurityPolicy` plugin is disabled 

- .golangci.yaml
- Dockerfile
- Makefile
- pkg/cmd/options.go
Update builder image golang 1.18.3 -> 1.19.1. 
The golangci_lint version was updated and minor lint warnings have been fixed, too.
```other operator
Update builder image golang `1.18.3` -> `1.19.1`
```
> Update builder image golang 1.18.3 -> 1.19.1

- go.mod
- pkg/controller/lifecycle/actuator.go
This PR adds a seccomp profile to pods running in the shoot for shoot k8s version >= 1.19.
Fixes #
```other operator
Pods running in the shoot now have their seccomp profile set to "RuntimeDefault". 
```
> Set seccomp profile to RuntimeDefault

- example/10-fake-shoot-controlplane.yaml
- example/30-cluster.yaml
- go.mod
- hack/api-reference/config.json
- hack/api-reference/config.md
- pkg/controller/lifecycle/actuator.go
Drop support for kubernetes < 1.20 for shoot networking filter extension
Part of https://github.com/gardener/gardener/issues/6911
```other operator
shoot-networking-filter no longer supports Shoots with Кubernetes version < 1.20.
```
> Drop support for kubernetes < 1.20 for shoot networking filter extension

- .ci/pipeline_definitions
- Dockerfile
Update builder image to golang:1.19.5
Also enabled clean-snapshot.
```other operator
Update builder image from `golang:1.19.4` to `golang:1.19.5`
```
> Update builder image to golang:1.19.5

- cmd/gardener-extension-shoot-networking-filter/app/app.go
- go.mod
- go.sum
- pkg/cmd/options.go
- pkg/controller/healthcheck/add.go
- vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/controller.go
- vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
- vendor/modules.txt
**How to categorize this PR?**
/area control-plane
/kind bug
For the reasoning, please check https://github.com/gardener/gardener/issues/6775#issuecomment-1432816749 and https://github.com/gardener/gardener/pull/7660.
We need to add the healthcheck controller back and add `ShootSystemComponentsHealthy` to `conditionTypesToRemove`.
Part of  https://github.com/gardener/gardener/issues/6775
```bugfix operator
The stale healthcheck conditions from the `shoot-networking-filter` extension are now properly cleaned up.
```
```other dependency
The following dependency is updated:
- github.com/gardener/gardener: v1.66.0 -> v1.66.1
```
> Vendor `gardener@1.66.1` and add `ShootSystemComponentsHealthy` to `conditionTypesToRemove`

- cmd/gardener-extension-shoot-networking-filter/app/app.go
- docs/usage/shoot-networking-filter.md
- pkg/apis/config/install/install.go
- pkg/controller/lifecycle/actuator.go
- pkg/controller/lifecycle/filter.go
- pkg/controller/lifecycle/filter_test.go
- pkg/controller/lifecycle/filterlistprovider.go
With blackhole routing ingress and egress traffic for configured IPs is blocked.
It can be enabled on per-shoot basis.
Fixes #
```feature user
With blackhole routing ingress and egress traffic for configured IPs is blocked.
It can be enabled on per-shoot basis.
```
> Make `blackholing` configureable per shoot.

- README.md
This PR fixes broken links in the documentation. The links were broken due to the [removal of the files being pointed to](https://github.com/gardener/egress-filter-refresher/commit/bc7d2ef8558f9c7658a5ba6eab837540ec7adf02#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557), replacing them with a single Dockerfile.
Fixes #
```doc developer
NONE
```
> Fixed broken links - 2023.06

- Dockerfile
Update golang to 1.20.5.
Fixes #
```other operator
Update golang to `1.20.5`.
```
> Update golang to 1.20.5

- pkg/constants/constants.go
- pkg/controller/lifecycle/actuator.go
Mount `/run/xtables.lock` to prevent concurrent modifications of iptables rules.
Fixes #
```feature user
Mount `/run/xtables.lock` to prevent concurrent modifications of iptables rules.
```
> Mount xtables.lock file.

- pkg/controller/lifecycle/actuator.go
current `egress-filter-applier` pod creations fail with:
```
Warning  FailedCreate  43m (x29 over 11h)    daemonset-controller  Error creating: pods "egress-filter-applier-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.capabilities.add: Invalid value: "NET_ADMIN": capability may not be added]
```
Fixes #
```feature user
fix egress-filter-applier pod …
```
> add hostPath in PSP - DaemonSet "kube-system/egress-filter-applier" is unhealthy

- go.mod
similar to https://github.com/gardener/gardener/pull/9564
Fixes #
```other operator
NONE
```
> Use x.y.0 versions of the Go Toolchain only

- .ci/pipeline_definitions
To allow for generation of ImageVector-Overwrites (required for deployments from different last-mile repositories), metadata allowing mapping to original image-references needs to be kept. Add this metadata for future releases to Component-Descriptor.
```other operator
Add OCM-Component-Descriptor-Labels required for ImageVector-Generation.
```
> add imagevector-labels for oci-images

- pkg/controller/lifecycle/actuator.go
/kind enhancement
This PR reduces the  `resources.requests.cpu` and `resources.requests.memory` of the `egress-filter-applier` container to `5m` and `20Mi`, respectively. This optimisation is based on the 95th percentile across all  containers of that component found in our landscapes. 
Previously the utilisation was at 0% (for CPU) and 21% (for memory).
Fixes #
```other operator
The `resources.requests.cpu` and `resources.requests.memory` of the `egress-filter-applier` container have been reduced to `5m` and `20Mi`, respectively.
```
> Reduce `egress-filter-applier` resource requests

- .gitignore
- Makefile
- hack/sast.sh
- pkg/cmd/options.go
- pkg/constants/constants.go
- pkg/controller/lifecycle/filterlistprovider.go
/area networking
/area security
/area compliance
/kind enhancement
This PR introduces `gosec` for Static Application Security Testing at Gardener and should replace other code scanners.
It uses the default ruleset of `gosec` from gardener/gardener as introduced in https://github.com/gardener/gardener/pull/9959.
Fixes #
Until https://github.com/gardener/gardener/pull/10642 is in a gardener/gardener release there is a small workaround necessary, which will be removed afterwards.
```other operator
`gosec` was introduced for Static Application Security Testing (SAST).
```
> Introduce `gosec` for Static Application Security Testing (SAST)

- Makefile
Remove `adjust-install-gosec` Makefile target as not needed anymore.
Fixes #
```other operator
NONE
```
> Remove `adjust-install-gosec` Makefile target

- .ci/pipeline_definitions
Fix pipeline_definitions: bump image for verify step to golang:1.24.1
Fixes #
```other operator
NONE
```
> Fix pipeline_definitions: bump image for verify step to golang:1.24.1

- hack/test-e2e-operator-local.sh
Fixes #
```other operator
NONE
```
> Adapt location of operator kubeconfig for e2e test.

- example/10-fake-shoot-controlplane.yaml
- example/30-cluster.yaml
- test/e2e/local/common_test.go
- test/e2e/operator/common_test.go
**How to categorize this PR?**
/kind cleanup
/area quality
Drop support for Shoots, Seeds and Gardens with Kubernetes version <= 1.28.
Part of https://github.com/gardener/gardener/issues/12409
N/A
```breaking operator
`shoot-networking-filter` no longer supports Shoots with Кubernetes version <= 1.28.
```
> Drop support for Shoots with Kubernetes version <= 1.28
